---
# From https://confluence.internal.salesforce.com/display/public/ZEN/Pipeline+Stages+In+Depth#PipelineStagesInDepth-Global.strata.ymlKeys
pipeline_template: docker/Jenkinsfile-1
email_reply_to: sfcdupstream@salesforce.com
docker_test_images:
  - sfci/sfcd/docker-spinnaker-build/sfcd/spinnaker-build:latest
# Convince strata to stop using snyk's default (and specific to maven) args
snyk_build_args: "''"
# Specify TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX since testcontainers uses
# docker.io by default, which isn't accessible from jenkins.  See
# https://www.testcontainers.org/features/image_name_substitution/#automatically-modifying-docker-hub-image-names.
#
# Disable front50-sql tests since they use a postgres docker image, and
# SalesforceImageNameSubstitutor doesn't know of an internal-to-Salesforce
# postgres image.
#
# gradle options match the upstream PR builds here:
# https://git.soma.salesforce.com/spinnaker/front50/blob/6417003054393807280f7b0aab16f0455ddec2cf/.github/workflows/pr.yml
#
# There's an opa policy that forbids access to /var/run/docker.sock.  Instead,
# use /var/run/docker-secondary.sock.  See
# https://salesforce-internal.slack.com/archives/CG2A365BK/p1659729614882769?thread_ts=1659726358.299829&cid=CG2A365BK
# for background.
unit_tests_command: gradleenv auto && TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE="/var/run/docker-secondary.sock" TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX="dva-registry.internal.salesforce.com/sfci/3pp/3pp/docker.io/" GRADLE_OPTS="-Dorg.gradle.daemon=false -Xmx2g -Xms2g" ./gradlew build -x :front50-sql:test front-web:distTar && spinnaker_git_tag.sh
docker_images:
    front50_release-1.23.x-sfcd: ./Dockerfile.sfcd
production_branch:
    - release-1.23.x-sfcd
promote_to_falcon: true
