---
# From https://confluence.internal.salesforce.com/display/public/ZEN/Pipeline+Stages+In+Depth#PipelineStagesInDepth-Global.strata.ymlKeys
pipeline_template: docker/Jenkinsfile-1
email_reply_to: sfcdupstream@salesforce.com
docker_test_images:
  - sfci/sfcd/docker-spinnaker-build/sfcd/spinnaker-build:latest
# Convince strata to stop using snyk's default (and specific to maven) args
snyk_build_args: "''"
# Specify TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX since testcontainers uses
# docker.io by default, which isn't accessible from jenkins.  See
# https://www.testcontainers.org/features/image_name_substitution/#automatically-modifying-docker-hub-image-names.
#
# Disable front50-sql and front50-web tests until testcontainers dependencies
# are present.  See https://git.soma.salesforce.com/3pp/3pp/pull/74 and
# https://git.soma.salesforce.com/3pp/3pp/pull/77.
#
# proxy information comes from
# https://git.soma.salesforce.com/sfcd/docker-spinnaker-build/blob/bd9266225fa66dc7d1838a5a8bcfc494ab969705/Dockerfile
# and
# https://git.soma.salesforce.com/sfcd/builds-shared/blob/0b2919641456edb62150aecace366ed05e6bf6bb/make/include/spinnaker.mk#L3
#
# other gradle options match the upstream PR builds here:
# https://git.soma.salesforce.com/spinnaker/front50/blob/6417003054393807280f7b0aab16f0455ddec2cf/.github/workflows/pr.yml
unit_tests_command: gradleenv auto && TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX="dva-registry.internal.salesforce.com/sfci/3pp/3pp/docker.io/" GRADLE_OPTS="-Dorg.gradle.daemon=false -Xmx2g -Xms2g" ./gradlew build -x :front50-sql:test -x :front50-web:test front-web:distTar && spinnaker_git_tag.sh
docker_images:
    front50_release-1.23.x-sfcd: ./Dockerfile.sfcd
production_branch:
    - release-1.23.x-sfcd
promote_to_falcon: true
